version: "3"

services:
  conductor:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    links:
      - mongo
    environment:
      dbhost: mongodb://mongo:27017/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
